config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  get 'home/index'
  root to: "readers/home#index"
  get '/blog/:id' => 'readers/posts#show', as: :blog_post

  scope module: 'authors' do
    resources :posts do
      resources :elements
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :title, :description, :header_image, presence: true
  validates :element_type, inclusion: { in: ['paragraph', 'image', 'video-enbed'] }

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :author
  has_many :elements

  has_one_attached :header_image

  scope :published, -> do
    where(published: true )
  end

  scope :most_recently_published, -> do
    order(published_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/elements_controller.rb
module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: [:update, :destroy]

    # POST /elements
    def create
      @element = @post.elements.build(element_params)

      if @element.save
        notice = nil
      else
        notice = @element.errors.full_messages.join(" .") << "."
      end
      redirect_to edit_post_path(@post), notice: notice
    end

    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
      redirect_to edit_post_path(@element.post)
    end

    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to edit_post_path(@element.post)
    end

    private
    # Use callbacks to share common setup or constraints between actions.

    def set_post
      @post = current_author.posts.find(params[:post_id])
    end

    def set_element
      @element = @post.elements.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_params
      params.require(:element).permit(:element_type, :content, :image)
    end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: [:edit, :update, :destroy]

    # GET /posts
    def index
      @posts = current_author.posts
    end

    # GET /posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
    end

    # POST /posts
    def create
      @post = current_author.posts.build(post_params)
      @post.author = current_author

      if @post.save
        redirect_to edit_post_path(@post)
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post)
      else
        render :edit
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :description, :header_image)
      end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!

  layout 'authors'
end

app/controllers/readers/home_controller.rb
module Readers
  class HomeController < ReadersController
    def index
      @posts = Post.published.most_recently_published
    end
  end
end

app/controllers/readers/posts_controller.rb
module Readers
  class PostsController < ReadersController

    def show
      @post = Post.published.find(params[:id])
    end
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  layout 'readers'
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !current_author.nil?
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/elements/update.js.erb
var element = document.getElementById('element-<%= @element.id %>-form');

element.classList.add('d-none')
element.previousElementSibling.classList.remove('d-none')

var html = "<div class='trix-content'><%= @element.content.body.html_safe %></div>"

element.previousElementSibling.innerHTML = html

app/views/authors/posts/_form.html.slim
= form_with(model: post, local: true) do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :header_image
    = f.file_field :header_image, class: 'form-control-file input-image-text'
    .mt-1
      - if post.header_image.present?
        small Current image:
        = image_tag(post.header_image, width: '100%')
  .actions = f.submit class: 'btn btn-primary btn-block'

app/views/authors/posts/edit.html.slim
.row
  .col-md-4
    = link_to 'Back', posts_path, class: 'btn btn-dark mb-3'
    .card
      .card-header
        h6.card-title.mb-0 Editing Post
      .card-body
        = render 'form', post: @post
      .card-footer
        - if @post.published?
          a.btn.btn-secondary.btn-block[
            href="#"
            data-reflex="click->PublisherReflex#unpublish"
            data-post-id="#{@post.id}"]
            | Unpublish
        - else
          a.btn.btn-dark.btn-block[
            href="#"
            data-reflex="click->PublisherReflex#publish"
            data-post-id="#{@post.id}"]
            | Publish
  .col-md-8
    .mb-3
      = form_with(model: [@post, @element], html: { class: 'float-left mr-1' }) do |form|
        = form.hidden_field :element_type, value: 'paragraph'
        = button_tag(type: 'submit', class: 'btn btn-secondary') do
          i.fas.fa-paragraph
      = form_with(model: [@post, @element]) do |form|
        = form.hidden_field :element_type, value: 'image'
        = button_tag(type: 'submit', class: 'btn btn-secondary') do
          i.fas.fa-image
    .card.mb-5
      .card-header.text-right
        - if @post.published?
          b
            | Published
          |  #{time_ago_in_words(@post.published_at)} ago
        - else
          | Unpublished
      .card-body.pt-5 data-controller="elements"
        - if @post.elements.none? { |element| element.persisted? }
          .p-4.text-center
            h2.text-secondary
              i.fas.fa-lightbulb
            p Click the icons above to add elements to this post.
        - else
          ul#elements data-action="drop->elements#sort"
            - @post.elements.order(position: :asc).each do |element|
              - if element.persisted?
                li.element-item data-id="#{ element.id }"
                  - if element.paragraph?
                    .mb-4.p-3.paragraph
                      .paragraph-content
                        - if element.content.present?
                          == element.content
                          br
                        - else
                          | Click to add content.
                          br
                      .paragraph-form.d-done.d-none id="element-#{ element.id }-form"
                        = form_with(model: [@post, element]) do |form|
                          = form.rich_text_area :content, id: "element_content_#{element.id}"
                          .mt-3.d-flex.justify-content-between
                            div
                              = form.submit "Save", class: 'btn btn-primary mr-1'
                              a href="#" class='cancel btn btn-secondary' Cancel
                            = link_to 'Delete', post_element_path(@post, element), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }
                  - elsif element.image?
                    .mb-4.p-3.image
                      - if element.image.present?
                        = link_to post_element_path(@post, element), method: :delete, class: 'delete-btn btn btn-dark mt-2 float-right', data: { confirm: 'Are you sure?' }
                         i.fas.fa-times
                        = image_tag(element.image)
                      - else
                        = form_with(model: [@post, element]) do |form|
                          = form.file_field :image
                          .mt-3
                            = form.submit "Save", class: 'btn btn-primary mr-1'
                            a href="#" class="cancel btn btn-secondary" Cancel

app/views/authors/posts/index.html.slim
h4.d-flex.justify-content-between.mb-4
  span Posts
  div
    = link_to 'New Post', new_post_path, class: 'btn btn-primary mr-3'
    = link_to 'Logout', destroy_author_session_path, method: :delete, class: 'btn btn-danger'

- @posts.each do |post|
  = link_to edit_post_path(post), class: 'text-decoration-none' do
    .card.mb-3.post-card
      .card-body
        .row
          .col-md-2
            - if post.header_image.present?
              .header-img style="background-image: url(#{url_for(post.header_image)});"
          .col-md-10
            - if post.published?
              span.badge.badge-primary.mb-3
                | Published
            - else
              span.badge.badge-secondary.mb-3
                | Unpublished
            h5.card-title.text-dark.mb-2 = post.title
            p.text-secondary.mb-0 = post.description

app/views/authors/posts/new.html.slim
.row
  .col-md-4
    = link_to 'Back', posts_path, class: 'btn btn-dark mb-3'
    .card
      .card-header
        h6.card-title.mb-0
          | New Post
      .card-body
        == render 'form', post: @post

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Sirius
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p.notice = notice
    p.alert = alert
    = yield

app/views/layouts/authors.html.slim
doctype html
html
  head
    title
      | Sirius
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag

    link[rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"]

    script[src="https://use.fontawesome.com/releases/v5.15.1/js/all.js"
    crossorigin="anonymous"]

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-light.authors
    .container
      p.notice = notice
      p.alert = alert
      = yield

app/views/layouts/readers.html.slim
doctype html
html
  head
    title
      | Sirius
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    link[rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"]

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body class="bg-light readers #{ controller_name } #{ action_name }"
    .container
      p.notice = notice
      p.alert = alert
      = yield

app/views/readers/home/index.html.slim
- if current_author.nil?
  h1
    | Welcome.
- else
  .row
    - @posts.each do |post|
      .col-md-6.col-lg-4
        .card.post-card
          .header-image style="background-image: url(#{url_for(post.header_image)})"
          .card-body.d-flex.flex-column
            h5.card-title = post.title
            p.card-text = truncate(post.description, length: 250)
            = link_to "Read Post", blog_post_path(post), class: 'btn btn-primary mt-auto'

app/views/readers/posts/show.html.slim
.row
  .col-lg-10.offset-lg-1
    .card.post-card.mb-5
      .header-image style="background-image: url(#{url_for(@post.header_image)})"
      .card-body
        .pl-5.pr-5.pt-4.pb-4
          h1.card-title.mb-5 = @post.title
          - @post.elements.each do |element|
            - if element.image?
              .image-element.mb-5
                = image_tag(element.image)
            - else
              .content-element
                = element.content